---
- name: Create file on hosts step 1
  hosts: web1
  become: yes
  tasks:
    - name: Creat—É file on web1
    file: &default
          path: /home/ubuntu/new.txt
          state: touch

- name: Create file on hosts step 2
  hosts: web2
  become: yes
  tasks:
    - name: Create file on web2
     file: 
      <<: *default

- name: Create file on hosts step 3
  hosts: DB
  become: yes
  tasks:
     file: 
      <<: *default
   